artifact_location: /Users/don/github-projects/mlflow_experiment_tracking/export MLFLOW_TRACKING_URI=http:/ec2-3-83-116-165.compute-1.amazonaws.com:5000/0
creation_time: 1718203072001
experiment_id: '0'
last_update_time: 1718203072001
lifecycle_stage: active
name: Default
